export const techDescriptions: Record<string, string> = {
  // Programming Languages
  "JavaScript": "A high-level, interpreted programming language that conforms to the ECMAScript specification.",
  "TypeScript": "A typed superset of JavaScript that compiles to plain JavaScript.",
  "Python": "An interpreted, high-level and general-purpose programming language.",

  // Frontend
  "React": "A JavaScript library for building user interfaces.",
  "ReactJS": "A JavaScript library for building user interfaces.",
  "HTML": "The standard markup language for documents designed to be displayed in a web browser.",
  "Next.js": "A React framework for building server-side rendered and static web applications.",
  "NextJS": "A React framework for building server-side rendered and static web applications.",
  "Redux": "A predictable state container for JavaScript apps.",
  "Tailwind CSS": "A utility-first CSS framework for rapidly building custom user interfaces.",
  "Tailwind UI": "A component library built on top of Tailwind CSS.",
  "Webpack": "A static module bundler for modern JavaScript applications.",
  "D3": "A JavaScript library for producing dynamic, interactive data visualizations in web browsers.",
  "AG Grid": "A feature-rich datagrid for React, Angular, Vue, and JavaScript.",
  "Context API": "A React structure that allows you to share state across the entire app.",
  "CSS": "A stylesheet language used to describe the presentation of a document written in a markup language like HTML.",
  "StoryBook": "An open source tool for developing UI components in isolation for React, Vue, and Angular.",
  "React Hooks": "Functions that let you “hook into” React state and lifecycle features from function components.",
  "MaterialUI": "A popular React UI framework.",
  "React Query": "A library for fetching, caching, synchronizing and updating server state in React applications.",
  "Turborepo": "A high-performance build system for JavaScript and TypeScript codebases.",
  "Vite": "A build tool that aims to provide a faster and leaner development experience for modern web projects.",
  "WebSocket": "A computer communications protocol, providing full-duplex communication channels over a single TCP connection.",
  "Figma": "A vector graphics editor and prototyping tool.",
  "SSR": "Server-Side Rendering is the ability of an application to contribute to displaying a web-page on the server instead of rendering it in the browser.",
  "Zod": "A TypeScript-first schema declaration and validation library.",
  "Tanstack Query": "A powerful data-synchronization library for React, Solid, Svelte and Vue.",
  "XState": "A library for creating, interpreting, and executing finite state machines and statecharts.",
  "Tanstack Virtual": "A library for virtualizing large lists and grids in React, Solid, Svelte and Vue.",
  "SSG": "Static Site Generation is the process of generating a full static HTML website based on raw data and a set of templates.",
  "WebGL": "A JavaScript API for rendering interactive 2D and 3D graphics within any compatible web browser.",
  "Three.js": "A cross-browser JavaScript library and application programming interface used to create and display animated 3D computer graphics in a web browser.",
  "Framer Motion": "A production-ready motion library for React.",
  "GSAP": "A robust JavaScript toolset that turns developers into animation superheroes.",
  "Turbopack": "An incremental bundler optimized for JavaScript and TypeScript, written in Rust.",
  "ESLint": "A pluggable and configurable linter tool for identifying and reporting on patterns in JavaScript.",
  "Prettier": "An opinionated code formatter.",

  // Backend
  "Node.js": "A JavaScript runtime built on Chrome's V8 JavaScript engine.",
  "NodeJS": "A JavaScript runtime built on Chrome's V8 JavaScript engine.",
  "ExpressJS": "A minimal and flexible Node.js web application framework that provides a robust set of features for web and mobile applications.",
  "tRPC": "A framework for building end-to-end typesafe APIs.",
  "Django": "A high-level Python Web framework that encourages rapid development and clean, pragmatic design.",
  "Go": "A statically typed, compiled programming language designed at Google.",
  "Rust": "A multi-paradigm programming language focused on performance and safety, especially safe concurrency.",
  "Edge Workers": "Functions that run on a global network of servers, close to your users.",

  // Databases & Data Management
  "PostgreSQL": "A powerful, open source object-relational database system.",
  "NoSQL": "A database that provides a mechanism for storage and retrieval of data that is modeled in means other than the tabular relations used in relational databases.",
  "MongoDB": "A source-available cross-platform document-oriented database program.",
  "GraphQL": "A query language for APIs and a runtime for fulfilling those queries with your existing data.",
  "REST": "An architectural style that defines a set of constraints to be used for creating web services.",
  "Hasura": "An open-source engine that connects to your databases & microservices and instantly gives you a production-ready GraphQL API.",
  "Prisma": "A next-generation ORM for Node.js and TypeScript.",
  "DynamoDB": "A fully managed proprietary NoSQL database service that supports key-value and document data structures.",
  "Apollo": "A platform for building a supergraph, a unified network of all your data, services, and capabilities.",
  "Redis": "An in-memory data structure store, used as a database, cache, and message broker.",
  "SQLite": "A C-language library that implements a small, fast, self-contained, high-reliability, full-featured, SQL database engine.",

  // Cloud & DevOps
  "Git": "A free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency.",
  "GitHub": "A provider of Internet hosting for software development and version control using Git.",
  "GitLab": "A web-based DevOps lifecycle tool that provides a Git-repository manager providing wiki, issue-tracking and continuous integration/continuous delivery pipeline features.",
  "CI/CD": "Continuous Integration and Continuous Delivery is a method to frequently deliver apps to customers by introducing automation into the stages of app development.",
  "AWS AppSync": "A fully managed service that makes it easy to develop GraphQL APIs by handling the heavy lifting of securely connecting to data sources like AWS DynamoDB, Lambda, and more.",
  "AWS Amplify": "A set of tools and services that can be used together or on their own, to help front-end web and mobile developers build scalable full stack applications, powered by AWS.",
  "AWS Lambda": "A serverless computing service that lets you run code without provisioning or managing servers.",
  "AWS EC2": "Amazon Elastic Compute Cloud is a service that provides secure, resizable compute capacity in the cloud.",
  "Docker": "A set of platform as a service products that use OS-level virtualization to deliver software in packages called containers.",
  "Vercel": "A cloud platform for static sites and Serverless Functions that fits perfectly with your workflow.",
  "Terraform": "An open-source infrastructure as code software tool.",
  "Kafka": "A distributed event streaming platform.",

  // Testing
  "Jest": "A delightful JavaScript Testing Framework with a focus on simplicity.",
  "Enzyme": "A JavaScript Testing utility for React that makes it easier to test your React Components' output.",
  "Cypress": "A next generation front end testing tool built for the modern web.",
  "React Testing Library": "A set of helpers that let you test React components without relying on their implementation details.",
  "TDD": "Test-driven development is a software development process that relies on the repetition of a very short development cycle.",

  // AI/Machine Learning
  "Ollama (Local LLM Deployment)": "A tool for running large language models locally.",
  "TensorFlow.js (Node)": "A library for machine learning in JavaScript.",
  "Upscaler.js (ESRGAN-Slim)": "A library for upscaling images in JavaScript.",
  "crewAI": "A framework for orchestrating role-playing, autonomous AI agents.",
  "OpenAI": "An AI research and deployment company. Their mission is to ensure that artificial general intelligence benefits all of humanity.",
  "LangChain": "A framework for developing applications powered by language models.",
  "PyTorch": "An open source machine learning library based on the Torch library.",
  "ONNX": "An open format built to represent machine learning models.",
  "NetworkX": "A Python package for the creation, manipulation, and study of the structure, dynamics, and functions of complex networks.",
  "Tree-sitter": "A parser generator tool and an incremental parsing library.",

  // Data & Analytics
  "ClickHouse": "A fast, open-source, column-oriented database management system for online analytical processing.",
  "OpenTelemetry": "A set of APIs, libraries, agents, and instrumentation to observe and understand the performance of your software.",

  // Other
  "WebAssembly": "A binary instruction format for a stack-based virtual machine. WASM is designed as a portable target for compilation of high-level languages like C/C++/Rust, enabling deployment on the web for client and server applications.",
  "Convex": "A backend platform that provides a real-time database, server functions, and file storage.",
  "Playwright": "A framework for Web Testing and Automation. It allows testing Chromium, Firefox and WebKit with a single API.",
  "eBPF": "A revolutionary technology with origins in the Linux kernel that can run sandboxed programs in an operating system kernel.",
};